version: '3.7'

services:
  swagger_ui:
    image: swaggerapi/swagger-ui:3.18.2
    container_name: swagger_ui
    volumes:
    - .:/usr/share/nginx/html/openapi
    ports:
    - 9009:8080
    networks:
    - app-network

  mysql:
    image: library/mysql:5.7
    expose:
    - 3306
    container_name: mysql
    env_file:
    - ./.env
    ports:
    - 3307:3306
    volumes:
    - ./.docker/mysql/dev:/var/lib/mysql
    networks:
    - app-network

  nginx:
    build:
      context: ./.docker/nginx/
    container_name: nginx
    ports:
    - 81:80
    restart: always
    volumes:
    - ./.docker/nginx/logs:/var/log/nginx/
    - .:/var/www/html
    depends_on:
    - php
    networks:
    - app-network

  php:
    build:
      context: ./.docker/php/
    container_name: php
    restart: always
    env_file:
    - ./.env
    volumes:
    - ./.docker/php/app/cache:/var/www/dev/app/cache/:rw
    - ./.docker/php/app/logs:/var/www/dev/app/logs/:rw
    - ./.docker/.composer:/var/www/.composer
    - .:/var/www/html
    depends_on:
    - mysql
    networks:
    - app-network

networks:
  app-network:
    name: app-network
    driver: bridge
