version: '3.7'

services:
  db:
    image: mysql/mysql-server:5.7
    env_file:
    - ./.env
    ports:
    - 3307:3306
    volumes:
    - ./.docker/mysql/dev:/var/lib/mysql

  nginx:
    build:
      context: ./.docker/nginx/
    ports:
    - 81:80
    restart: always
    volumes:
    - ./.docker/nginx/logs:/var/log/nginx/
    - .:/var/www/html
    depends_on:
    - php

  php:
    image: library/php:7.4-fpm-alpine
    restart: always
    env_file:
    - ./.env
    volumes:
    - ./.docker/php/app/cache:/var/www/dev/app/cache/:rw
    - ./.docker/php/app/logs:/var/www/dev/app/logs/:rw
    - ./.docker/.composer:/var/www/.composer
    - .:/var/www/html
    links:
    - db
